// set up default state
const defaultState = [
    {   name: 'Make a Plan!', 
        note: 'Figure out how to start learning to code.', 
        completedAt: 'Nov. 13th, 2016',
        newImage: './images/ClothHead.png',
        defaultImage: './images/pdDefaultHead.png',
        target: 'pdHead',
        tileImage: './images/TileTest',
        skillInfo: "I decided to see if coding was a good fit for me. I spent 8 hours the first day doing exercises on freeCodeCamp.org."     },
    {   name: 'Revise The Plan!', 
        note: 'After encountering obstacles, find a better way.', 
        completedAt: 'January 3rd, 2017',
        newImage: './images/ClothBody.png',
        defaultImage: './images/pdDefaultTorso.png',
        target: 'pdTorso',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'freeCodeCamp exercises were fun, but not providing me with the depth of knowledge I wanted. The challenges were beyond my ability after the exercises, so I realized that I needed a better foundation.'    },
    {   name: 'Harvard CS50x', 
        note: 'Go to Harvard! ... or sign up for the free online course.', 
        completedAt: 'December 18th, 2017',
        newImage: './images/ClothLegs.png',
        defaultImage: './images/pdDefaultLegs.png',
        target: 'pdLegs',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'I started Harvard CS50x to get a better grasp of fundamentals. Though my final grade was 96%, the course remains unfinished. Completing the final project of the course did not fit my needs at the time, so I continued my journey.'    },
    {   name: 'Legacy Front End Certification', 
        note: 'A certification from freeCodeCamp.org', 
        completedAt: 'May 10th, 2018',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultFeet.png',
        target: 'pdFeet',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'After CS50x, I returned to freeCodeCamp and found the challenge projects to be much more manageable. Learned Bootstrap, Sass, JQuery, React, and Redux.'    },
    {   name: 'JavaScript Algorithms and Data Structures', 
        note: 'Practice basic-to-advanced algorithms and data structures at freeCodeCamp.org', 
        completedAt: 'May 31st, 2018',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultFeet.png',
        target: 'pdFeet',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'Continuing with freeCodeCamp, I learned various sorting algorithms and different data structures.'    },
    {   name: 'Responsive Web Design', 
        note: 'Learn mobile design and CSS from freeCodeCamp.org', 
        completedAt: 'June 10th, 2018',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultFeet.png',
        target: 'pdFeet',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'The next section on freeCodeCamp revolved around making apps work with different screen sizes and layouts. Mostly a CSS-based certificate.'    },
    {   name: 'NEW Front End Certification', 
        note: 'The revised certification from freeCodeCamp.org', 
        completedAt: 'May 10th, 2018',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultFeet.png',
        target: 'pdFeet',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'freeCodeCamp updated their entire curriculum, and I set about filling in any gaps from what I had finished before the update. They added new Front End projects, so I completed them and earned the new Front End Certification.'    },
    {   name: 'MITx 6.00.1x', 
        note: '-Introduction to Computer Science and Programming Using Python', 
        completedAt: 'August 31st, 2018',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultFeet.png',
        target: 'pdFeet',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'After getting some certifications in the Front End, I decided to look into other fields to learn more. I chose to try Python and Data Science, so I signed up for the intro course on edX.org.'    },
    {   name: 'Data Visualization', 
        note: 'Learn how to use D3 for representing data from freeCodeCamp.org', 
        completedAt: 'October 5th, 2018',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultLHand.png',
        target: 'pdLHand',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'After the MITx course, I went back to freeCodeCamp to try their data science sections. Working with D3, I learned to model different sets of data in attractive ways.'    },
    {   name: 'MITx 6.00.2x', 
        note: '-Introduction to Computational Thinking and Data Science', 
        completedAt: 'October 10th, 2018',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultRHand.png',
        target: 'pdRHand',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'The follow-up course for Python Data Science at edX.org. I learned about modeling data and simulating experiments.'    },
    {   name: 'A Live Study with Teamwork', 
        note: 'Pet project for some pro coders as a React Front-End Developer', 
        completedAt: 'Unfinished :(',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultRHand.png',
        target: 'pdRHand',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'Through a random chance, a Cyber Security developer based in South Korea found me online and asked if I wanted to join a pet project. I was tasked with developing a React-based Front-End. I learned how to use Github during this time as it was the version control we used for the project. After 4 months of development, with a completed MVP, the project stalled due to a lack of time from other team members.'    },
    {   name: 'The Complete Node.js Developer Course', 
        note: 'Udemy course by Andrew Meade', 
        completedAt: 'February 7th, 2019',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultRHand.png',
        target: 'pdRHand',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'Before tackling the freeCodeCamp Back End certifications, I decided to try a paid course through Udemy for Node.js. I learned my lesson in the Front End about relying on simple exercises to learn.'    },
    {   name: 'APIs and Microservices', 
        note: 'freeCodeCamp Back End section.', 
        completedAt: 'March 21st, 2019',
        newImage: './images/TestImage1.png',
        defaultImage: './images/pdDefaultRHand.png',
        target: 'pdRHand',
        tileImage: './images/TileTest',
        tileActive: false,
        skillInfo: 'This certification focused on Node and Express, with heavy use of NPM modules and databases through Mongoose and MongoDB. Setting up servers and managing databases. Taking the Udemy course beforehand made this certification very easy to get.'   },
];

export default (state = defaultState, action) => {
    switch(action.type) {
        default:
            return state;
    };
};